# Generated by Django 6.0.1 on 2026-01-15 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agents', '0001_initial'),
        ('platform', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentstaff',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='platform.agent'),
        ),
        migrations.AddField(
            model_name='customer',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='platform.agent'),
        ),
        migrations.AddField(
            model_name='phone',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='platform.agent'),
        ),
        migrations.AddField(
            model_name='phone',
            name='platform_registry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='platform.platformphoneregistry'),
        ),
        migrations.AddField(
            model_name='sale',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='platform.agent'),
        ),
        migrations.AddField(
            model_name='sale',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agents.customer'),
        ),
        migrations.AddField(
            model_name='sale',
            name='phone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agents.phone'),
        ),
        migrations.AddField(
            model_name='sale',
            name='sold_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='agents.agentstaff'),
        ),
        migrations.AddIndex(
            model_name='agentstaff',
            index=models.Index(fields=['agent', 'status'], name='agent_staff_agent_i_4d3d9d_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['agent', 'phone_number'], name='customers_agent_i_61c07b_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['phone_number'], name='customers_phone_n_7d2329_idx'),
        ),
        migrations.AddIndex(
            model_name='phone',
            index=models.Index(fields=['agent'], name='phones_agent_i_36414f_idx'),
        ),
        migrations.AddIndex(
            model_name='phone',
            index=models.Index(fields=['imei'], name='phones_imei_5a3849_idx'),
        ),
        migrations.AddIndex(
            model_name='phone',
            index=models.Index(fields=['lifecycle_status'], name='phones_lifecyc_1b33d8_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['agent', 'status'], name='sales_agent_i_dd7531_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['customer'], name='sales_custome_acc50a_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['phone'], name='sales_phone_i_65ac17_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['status'], name='sales_status_a83c6f_idx'),
        ),
        migrations.AddConstraint(
            model_name='sale',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('phone',), name='one_active_sale_per_phone'),
        ),
    ]
