# Generated by Django 6.0.1 on 2026-01-15 17:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0002_initial'),
        ('platform', '0002_remove_agentbilling_agent_billi_billing_5e633b_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='phone',
            name='phones_agent_i_36414f_idx',
        ),
        migrations.RemoveIndex(
            model_name='phone',
            name='phones_lifecyc_1b33d8_idx',
        ),
        migrations.RemoveIndex(
            model_name='sale',
            name='sales_status_a83c6f_idx',
        ),
        migrations.AddField(
            model_name='agentstaff',
            name='commission_rate',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='agentstaff',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='phone',
            name='brand',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='phone',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='phone',
            name='last_enforcement_check',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='phone',
            name='purchase_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='phone',
            name='selling_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='phone',
            name='serial_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='completion_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='installment_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='installment_frequency',
            field=models.CharField(blank=True, default='weekly', max_length=20),
        ),
        migrations.AddField(
            model_name='sale',
            name='number_of_installments',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='sale_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='agentstaff',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_members', to='platform.agent'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='platform.agent'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phones', to='platform.agent'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='imei',
            field=models.CharField(db_index=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='phone',
            name='platform_registry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phones', to='platform.platformphoneregistry'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='platform.agent'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='agents.customer'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='phone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='agents.phone'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='sold_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='agents.agentstaff'),
        ),
        migrations.AddIndex(
            model_name='phone',
            index=models.Index(fields=['agent', 'lifecycle_status'], name='phones_agent_i_7d6032_idx'),
        ),
        migrations.AddIndex(
            model_name='phone',
            index=models.Index(fields=['platform_registry'], name='phones_platfor_a49fae_idx'),
        ),
        migrations.AddConstraint(
            model_name='sale',
            constraint=models.CheckConstraint(condition=models.Q(('sale_price__gt', 0), ('down_payment__gte', 0), ('total_payable__gt', 0)), name='positive_sale_amounts'),
        ),
        migrations.AddConstraint(
            model_name='sale',
            constraint=models.CheckConstraint(condition=models.Q(('balance_remaining__gte', 0), ('balance_remaining__lte', models.F('total_payable'))), name='valid_balance'),
        ),
    ]
