# Generated by Django 6.0.1 on 2026-01-15 16:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('role', models.CharField(choices=[('platform_admin', 'Platform Admin'), ('agent_owner', 'Agent Owner')], max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=255)),
                ('risk_score', models.IntegerField(default=0)),
                ('credit_limit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('monnify_public_key', models.TextField()),
                ('monnify_secret_key_encrypted', models.TextField()),
                ('monnify_contract_code', models.CharField(max_length=100)),
                ('monnify_webhook_secret', models.TextField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('restricted', 'Restricted'), ('disabled', 'Disabled')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'agents',
            },
        ),
        migrations.CreateModel(
            name='AgentBilling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billing_period_start', models.DateField()),
                ('billing_period_end', models.DateField()),
                ('phones_sold_count', models.PositiveIntegerField()),
                ('fee_per_phone', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_amount_due', models.DecimalField(decimal_places=2, max_digits=12)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(max_length=20)),
                ('invoice_number', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='platform.agent')),
            ],
            options={
                'db_table': 'agent_billing',
            },
        ),
        migrations.CreateModel(
            name='PlatformPhoneRegistry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imei', models.CharField(max_length=20, unique=True)),
                ('is_blacklisted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('current_agent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_phones', to='platform.agent')),
                ('first_registered_agent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='first_registrations', to='platform.agent')),
            ],
            options={
                'db_table': 'platform_phone_registry',
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='users_email_4b85f2_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role'], name='users_role_0ace22_idx'),
        ),
        migrations.AddIndex(
            model_name='agent',
            index=models.Index(fields=['status'], name='agents_status_f5ff61_idx'),
        ),
        migrations.AddIndex(
            model_name='agent',
            index=models.Index(fields=['created_at'], name='agents_created_697d3a_idx'),
        ),
        migrations.AddIndex(
            model_name='agentbilling',
            index=models.Index(fields=['agent', 'status'], name='agent_billi_agent_i_ca4c86_idx'),
        ),
        migrations.AddIndex(
            model_name='agentbilling',
            index=models.Index(fields=['billing_period_start'], name='agent_billi_billing_5e633b_idx'),
        ),
        migrations.AddIndex(
            model_name='platformphoneregistry',
            index=models.Index(fields=['imei'], name='platform_ph_imei_b66b75_idx'),
        ),
        migrations.AddIndex(
            model_name='platformphoneregistry',
            index=models.Index(fields=['is_blacklisted'], name='platform_ph_is_blac_321991_idx'),
        ),
    ]
