# Generated by Django 6.0.1 on 2026-01-15 17:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='agentbilling',
            name='agent_billi_billing_5e633b_idx',
        ),
        migrations.AddField(
            model_name='agent',
            name='business_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='credit_used',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='agent',
            name='registration_number',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='platformphoneregistry',
            name='blacklist_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='agent',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agent_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='agentbilling',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_records', to='platform.agent'),
        ),
        migrations.AlterField(
            model_name='platformphoneregistry',
            name='current_agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_phones', to='platform.agent'),
        ),
        migrations.AlterField(
            model_name='platformphoneregistry',
            name='first_registered_agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='first_registrations', to='platform.agent'),
        ),
        migrations.AlterField(
            model_name='platformphoneregistry',
            name='imei',
            field=models.CharField(db_index=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=255, unique=True),
        ),
        migrations.AddIndex(
            model_name='agent',
            index=models.Index(fields=['risk_score'], name='agents_risk_sc_c7a2ff_idx'),
        ),
        migrations.AddIndex(
            model_name='agentbilling',
            index=models.Index(fields=['billing_period_end'], name='agent_billi_billing_6916dc_idx'),
        ),
        migrations.AddIndex(
            model_name='agentbilling',
            index=models.Index(fields=['invoice_number'], name='agent_billi_invoice_6918bd_idx'),
        ),
        migrations.AddIndex(
            model_name='platformphoneregistry',
            index=models.Index(fields=['current_agent'], name='platform_ph_current_48704d_idx'),
        ),
    ]
