# Generated by Django 6.0.1 on 2026-01-15 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agents', '0002_initial'),
        ('enforcement', '0001_initial'),
        ('platform', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicecommand',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='platform.agent'),
        ),
        migrations.AddField(
            model_name='devicecommand',
            name='issued_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='agents.agentstaff'),
        ),
        migrations.AddField(
            model_name='devicecommand',
            name='phone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agents.phone'),
        ),
        migrations.AddField(
            model_name='devicecommand',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agents.sale'),
        ),
        migrations.AddIndex(
            model_name='devicecommand',
            index=models.Index(fields=['phone', 'status'], name='device_comm_phone_i_3d92eb_idx'),
        ),
        migrations.AddIndex(
            model_name='devicecommand',
            index=models.Index(fields=['status'], name='device_comm_status_dc8019_idx'),
        ),
        migrations.AddIndex(
            model_name='devicecommand',
            index=models.Index(fields=['expires_at'], name='device_comm_expires_0cb3d1_idx'),
        ),
    ]
