# Generated by Django 6.0.1 on 2026-01-15 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0003_remove_phone_phones_agent_i_36414f_idx_and_more'),
        ('enforcement', '0002_initial'),
        ('platform', '0002_remove_agentbilling_agent_billi_billing_5e633b_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='devicecommand',
            name='device_comm_status_dc8019_idx',
        ),
        migrations.AddField(
            model_name='devicecommand',
            name='acknowledged_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='devicecommand',
            name='device_response',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='devicecommand',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='devicecommand',
            name='issued_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='devicecommand',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_commands', to='platform.agent'),
        ),
        migrations.AlterField(
            model_name='devicecommand',
            name='issued_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_commands', to='agents.agentstaff'),
        ),
        migrations.AlterField(
            model_name='devicecommand',
            name='phone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commands', to='agents.phone'),
        ),
        migrations.AlterField(
            model_name='devicecommand',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commands', to='agents.sale'),
        ),
        migrations.AddIndex(
            model_name='devicecommand',
            index=models.Index(fields=['sale'], name='device_comm_sale_id_c61305_idx'),
        ),
    ]
