# Generated by Django 6.0.1 on 2026-01-15 16:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('audit', '0001_initial'),
        ('platform', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='agentauditlog',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='platform.agent'),
        ),
        migrations.AddField(
            model_name='platformauditlog',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='agentauditlog',
            index=models.Index(fields=['agent', 'created_at'], name='agent_audit_agent_i_23b4c0_idx'),
        ),
        migrations.AddIndex(
            model_name='agentauditlog',
            index=models.Index(fields=['actor', 'created_at'], name='agent_audit_actor_i_e3df50_idx'),
        ),
        migrations.AddIndex(
            model_name='agentauditlog',
            index=models.Index(fields=['entity_type', 'entity_id'], name='agent_audit_entity__1692ff_idx'),
        ),
        migrations.AddIndex(
            model_name='agentauditlog',
            index=models.Index(fields=['created_at'], name='agent_audit_created_c8cb14_idx'),
        ),
        migrations.AddIndex(
            model_name='platformauditlog',
            index=models.Index(fields=['user', 'created_at'], name='platform_au_user_id_4e798d_idx'),
        ),
        migrations.AddIndex(
            model_name='platformauditlog',
            index=models.Index(fields=['entity_type', 'entity_id'], name='platform_au_entity__cc5074_idx'),
        ),
        migrations.AddIndex(
            model_name='platformauditlog',
            index=models.Index(fields=['created_at'], name='platform_au_created_cc4725_idx'),
        ),
    ]
