# Generated by Django 6.0.1 on 2026-01-15 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agents', '0002_initial'),
        ('payments', '0001_initial'),
        ('platform', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentrecord',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='platform.agent'),
        ),
        migrations.AddField(
            model_name='paymentrecord',
            name='installment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.installmentschedule'),
        ),
        migrations.AddField(
            model_name='paymentrecord',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agents.sale'),
        ),
        migrations.AddIndex(
            model_name='installmentschedule',
            index=models.Index(fields=['sale', 'status'], name='installment_sale_id_3713c6_idx'),
        ),
        migrations.AddIndex(
            model_name='installmentschedule',
            index=models.Index(fields=['due_date'], name='installment_due_dat_55e0d6_idx'),
        ),
        migrations.AddIndex(
            model_name='installmentschedule',
            index=models.Index(fields=['status', 'due_date'], name='installment_status_673e45_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentrecord',
            index=models.Index(fields=['sale'], name='payment_rec_sale_id_c2bc16_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentrecord',
            index=models.Index(fields=['agent', 'status'], name='payment_rec_agent_i_f4e3cd_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentrecord',
            index=models.Index(fields=['monnify_reference'], name='payment_rec_monnify_eafac1_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentrecord',
            index=models.Index(fields=['created_at'], name='payment_rec_created_da8b43_idx'),
        ),
    ]
