# Generated by Django 6.0.1 on 2026-01-15 17:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0003_remove_phone_phones_agent_i_36414f_idx_and_more'),
        ('payments', '0002_initial'),
        ('platform', '0002_remove_agentbilling_agent_billi_billing_5e633b_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='installmentschedule',
            options={'ordering': ['due_date']},
        ),
        migrations.RemoveIndex(
            model_name='installmentschedule',
            name='installment_status_673e45_idx',
        ),
        migrations.RemoveIndex(
            model_name='paymentrecord',
            name='payment_rec_created_da8b43_idx',
        ),
        migrations.AddField(
            model_name='installmentschedule',
            name='installment_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='installmentschedule',
            name='paid_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymentrecord',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymentrecord',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='agents.customer'),
        ),
        migrations.AddField(
            model_name='paymentrecord',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymentrecord',
            name='payment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymentrecord',
            name='recorded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recorded_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='installmentschedule',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='agents.sale'),
        ),
        migrations.AlterField(
            model_name='paymentrecord',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='platform.agent'),
        ),
        migrations.AlterField(
            model_name='paymentrecord',
            name='installment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='payments.installmentschedule'),
        ),
        migrations.AlterField(
            model_name='paymentrecord',
            name='monnify_reference',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='paymentrecord',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='agents.sale'),
        ),
        migrations.AddIndex(
            model_name='paymentrecord',
            index=models.Index(fields=['installment'], name='payment_rec_install_00fb60_idx'),
        ),
        migrations.AddConstraint(
            model_name='paymentrecord',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='positive_payment_amount'),
        ),
    ]
